name: Node CI

on:
  push:
    branches:
      - master
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
env:
  EXPANDINIZR_DIR: /home/runner/work/github.expandinizr.userstyles/github.expandinizr.userstyles/github.expandinizr

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - run: pwd
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        repository: thecodejunkie/github.expandinizr
        path: ${{ env.EXPANDINIZR_DIR }}
        ref: master
        # ref: ${{ github.ref }}
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: npm install
      run: |
        set -x
        export PATH="$PATH:${{ env.EXPANDINIZR_DIR }}/node_modules/.bin"

        npm install -C ${{ env.EXPANDINIZR_DIR }}

        patch -p1 -d ${{ env.EXPANDINIZR_DIR }} -i $PWD/userstyles.patch

        gulp styles

        version="${GITHUB_REF#refs/tags/}"
        sed -i -E "s:\{env\.GITHUB_REF\}:$version:" build/github.user.css
      env:
        CI: true

    - name: Would be creating a release
      run: |
        ls -la build/github.user.css
        cat build/github.user.css
      if: "!startsWith( github.ref, 'refs/tags/v' )"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
      if: startsWith( github.ref, 'refs/tags/v' )

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/github.user.css
        asset_name: github.user.css
        asset_content_type: text/css
      if: startsWith( github.ref, 'refs/tags/v' )
